// pages/api/export-report.js
// ExportGuard – Professional CBSA Compliance Report

import PDFDocument from 'pdfkit';

export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const analysis = req.body; // you post the result object here

  if (!analysis) {
    return res.status(400).json({ error: 'Missing analysis data' });
  }

  try {
    const pdf = generateExportGuardReport(analysis);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="ExportGuard-Report-${new Date()
        .toISOString()
        .split('T')[0]}.pdf"`
    );

    pdf.pipe(res);
    pdf.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
}

function generateExportGuardReport(analysisData) {
  const doc = new PDFDocument({
    size: 'letter',
    margin: 50,
    bufferPages: true,
  });

  const colors = {
    primary: '#1F3A4C',
    accent: '#208E9F',
    success: '#217D8D',
    warning: '#D97706',
    neutral: '#6B7280',
    lightGray: '#F3F4F6',
    border: '#E5E7EB',
  };

  addCoverPage(doc, colors);
  doc.addPage();
  addDisclaimerPage(doc, colors);
  doc.addPage();
  addExecutiveSummary(doc, colors, analysisData);
  doc.addPage();
  addDetailedAnalysis(doc, colors, analysisData);
  doc.addPage();
  addComplianceChecklist(doc, colors);
  doc.addPage();
  addCBSAGuide(doc, colors);
  doc.addPage();
  addRecordRetention(doc, colors);

  return doc;
}

// -------- COVER PAGE --------
function addCoverPage(doc, colors) {
  doc
    .fontSize(36)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('ExportGuard', 50, 90);

  doc
    .fontSize(14)
    .font('Helvetica')
    .fillColor(colors.accent)
    .text('AI Export Compliance Workstation', 50, 135);

  doc
    .strokeColor(colors.accent)
    .lineWidth(2)
    .moveTo(50, 160)
    .lineTo(545, 160)
    .stroke();

  doc
    .fontSize(24)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Export Compliance Analysis Report', 50, 210, {
      width: 495,
      align: 'center',
    });

  doc
    .fontSize(11)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      `Report Date: ${new Date().toLocaleDateString('en-CA', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`,
      50,
      270
    );
  doc.text('Report Type: CBSA Export Documentation Review', 50, 290);
  doc.text('Status: Generated by ExportGuard AI System', 50, 310);

  doc.rect(50, 350, 495, 110).fillAndStroke(colors.lightGray, colors.border);
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Export Shipment Snapshot', 60, 362);

  doc.fontSize(9).font('Helvetica').fillColor(colors.neutral);
  doc.text('Exporter: [Detected from invoice]', 60, 382);
  doc.text('Destination: [Detected from invoice]', 60, 397);
  doc.text('Invoice value (approx.): [From analysis]', 60, 412);
  doc.text('Reporting method: CERS (recommended)', 60, 427);

  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'This report is generated for export compliance guidance and should be reviewed by qualified customs professionals.',
      50,
      500,
      { width: 495, align: 'center' }
    );
  doc.text('© ExportGuard AI 2025 | Confidential', 50, 520, {
    width: 495,
    align: 'center',
  });
}

// -------- DISCLAIMER --------
function addDisclaimerPage(doc, colors) {
  heading(doc, colors, 'Legal Disclaimer & Notice');

  section(doc, colors, 'Disclaimer of Liability');
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'This ExportGuard report is a guidance document only and is not legal advice. You should consult a customs broker, trade lawyer, or CBSA official before relying on this report for any export decision.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(1);

  section(doc, colors, 'Responsibility of Exporter');
  doc.text(
    'The exporter remains responsible for providing true, accurate, and complete export information to the Canada Border Services Agency (CBSA) within prescribed timeframes under the Reporting of Exported Goods Regulations.',
    50,
    doc.y,
    { width: 495 }
  );

  doc.moveDown(1);

  section(doc, colors, 'Key CBSA References');
  bulletList(doc, colors, [
    'Memorandum D20-1-1: Exporter Reporting (cbsa-asfc.gc.ca)',
    'Reporting of Exported Goods Regulations (SOR/91-17)',
    'Customs Act (R.S.C. 1985, c. C-52)',
    'Canadian Export Reporting System (CERS) User Guide',
  ]);

  doc.moveDown(1);

  section(doc, colors, 'Confidentiality & Retention');
  doc.text(
    'Keep this report confidential and retain it, together with your export records, for at least 6 years in Canada in case of CBSA audit.',
    50,
    doc.y,
    { width: 495 }
  );
}

// -------- EXECUTIVE SUMMARY --------
function addExecutiveSummary(doc, colors, data) {
  heading(doc, colors, 'Executive Summary');

  section(doc, colors, 'Overview');
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'ExportGuard has analyzed your commercial invoice and export details against CBSA export reporting rules to highlight risks, gaps, and next steps for compliance.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(0.8);

  section(doc, colors, 'Key Findings');
  const top = doc.y;
  doc.rect(50, top, 495, 65).fillAndStroke(colors.lightGray, colors.border);

  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.success)
    .text('Preliminary compliance status: 70–85% aligned', 60, top + 10);

  doc.fontSize(9).font('Helvetica').fillColor(colors.neutral);
  doc.text('Documentation: mostly complete.', 60, top + 28);
  doc.text('Classification (HS): requires confirmation.', 60, top + 42);
  doc.text('Action: file an export declaration in CERS.', 60, top + 56);

  doc.y = top + 80;
  section(doc, colors, 'Critical Next Steps');
  bulletList(doc, colors, [
    'Confirm your Business Number (BN) and export program (RM).',
    'Assign the correct 8‑digit Canadian HS code for each line item.',
    'Submit an export declaration through the CERS portal.',
    'Obtain Proof of Report (POR) number and give it to your carrier.',
  ]);
}

// -------- DETAILED ANALYSIS --------
function addDetailedAnalysis(doc, colors, data) {
  heading(doc, colors, 'Detailed Analysis');

  section(doc, colors, 'Invoice & Data Elements');
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'Core invoice elements ExportGuard expects for CBSA export reporting are listed below. Use this as a quick validation checklist.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(0.5);

  const col1X = 50;
  const col2X = 270;
  doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.primary);
  doc.text('Field', col1X, doc.y);
  doc.text('Status (example)', col2X, doc.y);

  doc
    .strokeColor(colors.border)
    .lineWidth(1)
    .moveTo(col1X, doc.y + 15)
    .lineTo(col1X + 445, doc.y + 15)
    .stroke();

  doc.fontSize(8).font('Helvetica').fillColor(colors.neutral);
  let y = doc.y + 20;
  const rows = [
    ['Exporter name & address', '✓ Present'],
    ['Importer / consignee', '✓ Present'],
    ['Full commodity description', '⚠ Clarify if generic'],
    ['HS code (8‑digit)', '⚠ To be confirmed'],
    ['Invoice value (currency)', '✓ Present'],
    ['Country of origin', '✓ Present'],
    ['Destination country', '✓ Present'],
    ['Incoterms (FOB/CIF/DDP etc.)', '✓ Present'],
  ];

  rows.forEach(([field, status]) => {
    doc.text(field, col1X, y);
    doc.text(status, col2X, y);
    y += 14;
  });

  doc.y = y + 6;

  section(doc, colors, 'Timing by Mode of Transport');
  doc.fontSize(8).font('Helvetica-Bold').fillColor(colors.primary);
  const tx = 50;
  const tw = 150;
  doc.text('Mode', tx, doc.y);
  doc.text('CBSA timing rule', tx + tw, doc.y);
  doc.text('Key documents', tx + tw * 2, doc.y);
  doc.moveDown(0.6);
  doc
    .strokeColor(colors.border)
    .lineWidth(0.5)
    .moveTo(tx, doc.y)
    .lineTo(tx + 445, doc.y)
    .stroke();

  doc.fontSize(8).font('Helvetica').fillColor(colors.neutral);
  const modes = [
    ['Air', '≥ 2 hours before loading', 'CERS POR + invoice'],
    ['Marine', '≥ 48 hours before loading', 'CERS POR + bill of lading'],
    ['Rail', '≥ 2 hours before loading', 'CERS POR + waybill'],
    ['Highway', 'Before export', 'CERS POR + invoice'],
  ];
  modes.forEach(([m, t, d]) => {
    doc.text(m, tx, doc.y);
    doc.text(t, tx + tw, doc.y);
    doc.text(d, tx + tw * 2, doc.y);
    doc.moveDown(0.6);
  });
}

// -------- CHECKLIST --------
function addComplianceChecklist(doc, colors) {
  heading(doc, colors, 'Export Compliance Checklist');

  section(doc, colors, 'Before filing in CERS');
  bulletList(doc, colors, [
    'Business Number (BN) and export RM program are active.',
    'CERS portal account created and tested.',
    'All invoice data matches packing list and commercial contract.',
    'HS codes confirmed with Canadian Export Classification (StatCan).',
    'Country of origin and destination confirmed.',
    'Incoterms agreed with buyer and reflected on invoice.',
    'Controlled / restricted goods screened against Export Control List.',
    'Any export permits or licenses obtained (if required).',
  ]);

  doc.moveDown(0.8);
  section(doc, colors, 'At time of export');
  bulletList(doc, colors, [
    'Export declaration submitted in CERS.',
    'Proof of Report (POR) number received.',
    'POR and commercial invoice provided to the carrier.',
  ]);
}

// -------- CBSA GUIDE --------
function addCBSAGuide(doc, colors) {
  heading(doc, colors, 'CBSA Export Requirements Guide');

  section(doc, colors, 'Who must report?');
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'Most commercial exports from Canada valued at more than CAD $2,000 to non‑US destinations, or any controlled goods, must be reported to the CBSA using an export declaration.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(0.8);
  section(doc, colors, 'Key references (read online)');
  bulletList(doc, colors, [
    'Exporters’ Guide to Reporting: https://www.cbsa-asfc.gc.ca/services/export/guide-eng.html',
    'CERS User Guide: https://www.cbsa-asfc.gc.ca/services/export/cers-guide-scde-eng.html',
    'Memorandum D20-1-1: Exporter Reporting (search on cbsa-asfc.gc.ca)',
    'EDM9-3-1 Export Documentation (CRA): https://www.canada.ca/.../edm9-3-1.html',
  ]);

  doc.moveDown(0.8);
  section(doc, colors, 'Penalties (high level)');
  bulletList(doc, colors, [
    'Administrative Monetary Penalties (AMPS) for late/missing declarations.',
    'Detention or seizure of goods at the border.',
    'Possible prosecution for serious or repeated violations.',
  ]);
}

// -------- RECORD RETENTION --------
function addRecordRetention(doc, colors) {
  heading(doc, colors, 'Record Retention & Audit Trail');

  section(doc, colors, 'Minimum 6‑year retention');
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'Keep all export records in Canada for at least 6 years so they can be provided to CBSA in case of audit.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(0.6);
  section(doc, colors, 'Keep at least these documents');
  bulletList(doc, colors, [
    'Commercial invoice and packing list.',
    'Export declaration (CERS confirmation).',
    'Proof of Report (POR) number.',
    'Bills of lading / waybills / air waybills.',
    'Any export permits, licenses, or certificates.',
    'Contracts, purchase orders, and key correspondence.',
  ]);

  doc.moveDown(1.2);
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('End of ExportGuard Compliance Report', 50, doc.y, {
      width: 495,
      align: 'center',
    });
}

// -------- HELPERS --------
function heading(doc, colors, text) {
  doc
    .fontSize(16)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text(text, 50, doc.y || 50);
  doc
    .strokeColor(colors.accent)
    .lineWidth(2)
    .moveTo(50, doc.y + 4)
    .lineTo(545, doc.y + 4)
    .stroke();
  doc.moveDown(1.2);
}

function section(doc, colors, text) {
  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text(text, 50, doc.y);
  doc.moveDown(0.4);
}

function bulletList(doc, colors, items) {
  doc.fontSize(9).font('Helvetica').fillColor(colors.neutral);
  items.forEach((item) => {
    doc.text(`• ${item}`, 60, doc.y, { width: 435 });
    doc.moveDown(0.3);
  });
}
