// pages/api/export-report.js
// Professional ExportGuard CBSA Compliance Report Generator

import PDFDocument from 'pdfkit';

export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const analysis = req.body; // you’re currently posting the whole result object

  if (!analysis) {
    return res.status(400).json({ error: 'Missing analysis data' });
  }

  try {
    const pdf = generateExportGuardReport(analysis);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="ExportGuard-Report-${new Date()
        .toISOString()
        .split('T')[0]}.pdf"`
    );

    pdf.pipe(res);
    pdf.end();
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
}

function generateExportGuardReport(analysisData) {
  const doc = new PDFDocument({
    size: 'letter',
    margin: 50,
    bufferPages: true,
  });

  const colors = {
    primary: '#1F3A4C',
    accent: '#208E9F',
    success: '#217D8D',
    warning: '#D97706',
    error: '#DC2626',
    neutral: '#6B7280',
    lightGray: '#F3F4F6',
    border: '#E5E7EB',
  };

  // PAGE 1: COVER PAGE
  addCoverPage(doc, colors);

  // PAGE 2: DISCLAIMER
  doc.addPage();
  addDisclaimerPage(doc, colors);

  // PAGE 3: EXECUTIVE SUMMARY
  doc.addPage();
  addExecutiveSummary(doc, colors, analysisData);

  // PAGE 4: DETAILED ANALYSIS
  doc.addPage();
  addDetailedAnalysis(doc, colors, analysisData);

  // PAGE 5: COMPLIANCE FINDINGS
  doc.addPage();
  addComplianceFindings(doc, colors, analysisData);

  // PAGE 6: RECOMMENDATIONS
  doc.addPage();
  addRecommendations(doc, colors, analysisData);

  // PAGE 7: COMPLIANCE CHECKLIST
  doc.addPage();
  addComplianceChecklist(doc, colors);

  // PAGE 8: CBSA GUIDE
  doc.addPage();
  addCBSAGuide(doc, colors);

  // PAGE 9: FORMS & RESOURCES
  doc.addPage();
  addFormsAndResources(doc, colors);

  // PAGE 10: GLOSSARY
  doc.addPage();
  addGlossary(doc, colors);

  // PAGE 11: RECORD RETENTION
  doc.addPage();
  addRecordRetention(doc, colors);

  return doc;
}

// ---------- COVER PAGE ----------
function addCoverPage(doc, colors) {
  doc
    .fontSize(36)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('ExportGuard', 50, 100);

  doc
    .fontSize(14)
    .font('Helvetica')
    .fillColor(colors.accent)
    .text('AI Export Compliance Workstation', 50, 145);

  doc
    .strokeColor(colors.accent)
    .lineWidth(2)
    .moveTo(50, 165)
    .lineTo(545, 165)
    .stroke();

  doc
    .fontSize(28)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Export Compliance Analysis Report', 50, 220, {
      width: 495,
      align: 'center',
    });

  doc
    .fontSize(11)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      `Report Date: ${new Date().toLocaleDateString('en-CA', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`,
      50,
      280
    );
  doc.text('Report Type: CBSA Export Documentation Review', 50, 300);
  doc.text('Status: Generated by ExportGuard AI System', 50, 320);

  doc.rect(50, 360, 495, 120).fillAndStroke(colors.lightGray, colors.border);
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text('Export Shipment Details', 60, 375);

  doc.fontSize(9).font('Helvetica').fillColor(colors.neutral);
  doc.text('Commodity: Commercial goods (see invoice for specifics)', 60, 395);
  doc.text('Destination: [Per analysis]', 60, 412);
  doc.text('Exporter Type: Small-to-Medium Business (SMB)', 60, 429);
  doc.text('Reporting Method: CERS (Canadian Export Reporting System)', 60, 446);

  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'This report is generated for export compliance guidance and should be reviewed by qualified customs professionals.',
      50,
      520,
      { width: 495, align: 'center' }
    );
  doc.text('© ExportGuard AI 2025 | Confidential Document', 50, 540, {
    width: 495,
    align: 'center',
  });
}

// ---------- DISCLAIMER ----------
function addDisclaimerPage(doc, colors) {
  heading(doc, colors, 'Legal Disclaimer & Notice', 1);

  section(doc, colors, 'Disclaimer of Liability', 2);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'This report is prepared by ExportGuard AI as a guidance document only and is not legal advice. Exporters must consult with qualified customs brokers, trade lawyers, or CBSA officials for authoritative guidance specific to their situation.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(1);

  section(doc, colors, 'Responsibility of Exporter', 2);
  doc.text(
    'You remain responsible for providing true, accurate, and complete information to the Canada Border Services Agency (CBSA) within prescribed timeframes under the Reporting of Exported Goods Regulations.',
    50,
    doc.y,
    { width: 495 }
  );

  doc.moveDown(1);

  section(doc, colors, 'CBSA Memoranda & Regulations', 2);
  doc.text(
    'Key CBSA and federal references that underpin this report include:',
    50,
    doc.y,
    { width: 495 }
  );
  doc.moveDown(0.5);
  bulletList(doc, colors, [
    'Memorandum D20-1-1: Exporter Reporting (cbsa-asfc.gc.ca)',
    'Reporting of Exported Goods Regulations (SOR/91-17)',
    'Customs Act (R.S.C. 1985, c. C-52)',
    'Canadian Export Reporting System (CERS) User Guide',
  ]);

  doc.moveDown(1);

  section(doc, colors, 'Document Confidentiality', 2);
  doc.text(
    'This report contains confidential business information. Keep it secure and retain it for 6 years as required by Canadian export regulations.',
    50,
    doc.y,
    { width: 495 }
  );
}

// ---------- EXECUTIVE SUMMARY ----------
function addExecutiveSummary(doc, colors, data) {
  heading(doc, colors, 'Executive Summary', 1);

  section(doc, colors, 'Overview', 2);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'This report summarizes ExportGuard’s analysis of your commercial invoice and export documentation against CBSA export reporting requirements.',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(1);

  section(doc, colors, 'Key Findings', 2);

  const boxTop = doc.y;
  doc.rect(50, boxTop, 495, 70).fillAndStroke(colors.lightGray, colors.border);
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.success)
    .text('✓ Analysis Complete', 60, boxTop + 10);

  doc.fontSize(9).font('Helvetica').fillColor(colors.neutral);
  doc.text('Documentation Status: Requires review', 60, boxTop + 26);
  doc.text('HS Code Classification: Pending confirmation', 60, boxTop + 41);
  doc.text('Recommended Action: Submit export declaration in CERS', 60, boxTop + 56);

  doc.y = boxTop + 90;
  doc.moveDown(0.5);

  section(doc, colors, 'Critical Next Steps', 2);
  bulletList(doc, colors, [
    'Verify all invoice details match packing list and shipment.',
    'Classify goods using Canadian Export Classification (HS code).',
    'Ensure Business Number (BN) and export RM program are active.',
    'Submit export declaration via CERS within required timeframes.',
    'Provide Proof of Report (POR) number to your carrier.',
  ]);
}

// ---------- DETAILED ANALYSIS ----------
function addDetailedAnalysis(doc, colors, data) {
  heading(doc, colors, 'Detailed Compliance Analysis', 1);

  section(doc, colors, 'Invoice & Documentation Review', 2);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor(colors.neutral)
    .text(
      'The following core data elements were checked in your invoice and supporting documents:',
      50,
      doc.y,
      { width: 495 }
    );

  doc.moveDown(0.5);

  const col1X = 50;
  const col2X = 280;

  doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.primary);
  doc.text('Field', col1X, doc.y);
  doc.text('Status', col2X, doc.y);

  doc
    .strokeColor(colors.border)
    .lineWidth(1)
    .moveTo(col1X, doc.y + 15)
    .lineTo(col1X + 445, doc.y + 15)
    .stroke();

  doc.fontSize(8).font('Helvetica').fillColor(colors.neutral);
  let y = doc.y + 20;

  const rows = [
    ['Exporter information', '✓ Complete'],
    ['Importer / consignee', '✓ Complete'],
    ['Commodity description', '⚠ Clarify for HS coding'],
    ['HS code classification', '⚠ Pending'],
    ['Invoice value (CAD)', '✓ Confirmed'],
    ['Country of origin', '✓ Confirmed'],
    ['Destination country', '✓ Complete'],
    ['Incoterms', '✓ Stated'],
  ];

  rows.forEach((row) => {
    doc.text(row[0], col1X, y);
    doc.text(row[1], col2X, y);
    y += 15;
  });

  doc.y = y + 5;
  doc.moveDown(0.5);

  section(doc, colors, 'Export Declaration Requirements', 2);
  doc.text(
    'For most commercial exports over CAD $2,000 (non‑US destinations) or for controlled goods, an export declaration is mandatory.',
    50,
    doc.y,
    { width: 495 }
  );
  doc.moveDown(0.5);
  bulletList(doc, colors, [
    'Export declaration via CERS is generally required.',
    'Export permit may be required if goods fall under Export Control List.',
    'Certificate of Origin may be needed to claim trade agreement benefits.',
    'Proof of Report (POR) number must be obtained and given to carrier.',
  ]);

  doc.moveDown(0.5);
  section(doc, colors, 'Mode of Transport & Timing', 2);

  doc.fontSize(8).font('Helvetica-Bold').fillColor(colors.primary);
  const tx = 50;
  const tw = 150;
  doc.text('Mode', tx, doc.y);
  doc.text('Timing', tx + tw, doc.y);
  doc.text('Key documentation', tx + tw * 2, doc.y);
  doc.moveDown(0.7);

  doc
    .strokeColor(colors.border)
    .lineWidth(0.5)
    .moveTo(tx, doc.y)
    .lineTo(tx + 445, doc.y)
    .stroke();

  doc.fontSize(8).font('Helvetica').fillColor(colors.neutral);
  const modes = [
    { mode: 'Air', timing: '≥ 2 hours before loading', docs: 'CERS POR + invoice' },
    { mode: 'Marine', timing: '≥ 48 hours before loading', docs: 'CERS POR + bill of lading' },
    { mode: 'Rail', timing: '≥ 2 hours before loading', docs: 'CERS POR + rail waybill' },
    { mode: 'Highway', timing: 'Before export', docs: 'CERS POR + invoice' },
  ];

  modes.forEach((m) => {
    doc.text(m.mode, tx, doc.y);
    doc.text(m.timing, tx + tw, doc.y);
    doc.text(m.docs, tx + tw * 2, doc.y);
    doc.moveDown(0.7);
  });
}

// ---------- COMPLIANCE FINDINGS ----------
function addComplianceFindings(doc, colors, data) {
  heading(doc, colors, 'Compliance Status & Findings', 1);

  section(doc, colors, 'Overall Compliance Score', 2);

  const barWidth = 300;
  const score = 78; // placeholder – can be derived from analysisData

  const barTop = doc.y;
  doc.rect(50, barTop, barWidth, 20).stroke();
  doc.rect(50, barTop, (barWidth * score) / 100, 20).fill(colors.success);
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor(colors.primary)
    .text(`${score}% compliant (preliminary)`, 360, barTop + 2);

  doc.y = barTop + 30;
  doc.moveDown(0.5);

  section(doc, colors, 'Findings by Category', 2);

  const findings = [
    {
      category: 'Documentation',
      status: 'Mostly complete',
      items: ['Commercial invoice present', 'Packing list present', 'Values and currencies clear'],
    },
    {
      category: 'Classification',
      status: 'Needs review',
      items: ['HS code not yet finalized', 'Origin confirmation recommended'],
    },
    {
      category: 'CBSA registration',
      status: 'To confirm',
      items: ['BN and export RM program should be verified as active'],
    },
    {
      category: 'Permits & controls',
      status: 'No obvious red flags',
      items: ['No restricted items detected based on description (preliminary only)'],
    },
  ];

  findings.forEach((f) => {
    const top = doc.y;
    doc.rect(50, top, 495, 60).fillAndStroke(colors.lightGray, colors.border);
    doc
      .fontSize(9)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text(f.category, 60, top + 8);
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor(colors.warning)
      .text(f.status, 420, top + 8);

    doc.fontSize(8).font('Helvetica').fillColor(colors.neutral);
    let yy = top + 25;
    f.items.forEach((item) => {
      doc.text(`• ${item}`, 60, yy);
      yy += 11;
    });

    doc.y = top + 70;
    doc.moveDown(0.3);
  });
}

// ---------- RECOMMENDATIONS ----------
function addRecommendations(doc, colors, data) {
  heading(doc, colors, 'Recommendations & Action Plan', 1);

  section(doc, colors, 'Priority Actions (before export)', 2);

  const actions =
